# Unique ID for your project in SonarCloud
# Format is always: organization_reponame
sonar.projectKey=moelgenady_DevOps-HiveBox

# Your SonarCloud organization name
# Same as your GitHub username
sonar.organization=moelgenady

# Display name shown in SonarCloud dashboard
sonar.projectName=DevOps-HiveBox

# Your app version — matches APP_VERSION in app.py
sonar.projectVersion=0.0.2

# Where your source code lives
# SonarCloud only scans this folder
sonar.sources=src

# Where your tests live
# SonarCloud uses this to measure test coverage
sonar.tests=tests

# Which Python version you use
sonar.python.version=3.12