apiVersion: v1
kind: ConfigMap
metadata:
  name: hivebox-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  SENSEBOX_IDS: {{ .Values.config.senseboxIds | quote }}
  VALKEY_HOST: {{ .Values.config.valkeyHost | quote }}
  VALKEY_PORT: {{ .Values.config.valkeyPort | quote }}
  MINIO_ENDPOINT: {{ .Values.config.minioEndpoint | quote }}
  MINIO_BUCKET: {{ .Values.config.minioBucket | quote }}
  APP_VERSION: {{ .Values.app.version | quote }}
