#SPDX-License-Identifier: MIT-0
---
# vars file for roles/nginx-ingress
ingress_nginx_namespace: "ingress-nginx"
ingress_nginx_release_name: "ingress-nginx"
ingress_nginx_repo_url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml"
# ingress_nginx_repo_url: "https://kubernetes.github.io/ingress-nginx"
# ingress_nginx_chart_ref: "ingress-nginx/ingress-nginx"
# ingress_nginx_chart_version: "4.10.1" # Pinning to a known stable release