apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: hivebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 9000

          volumeMounts:
            - name: minio-credentials
              mountPath: /etc/minio/secrets
              readOnly: true
          env:
            - name: MINIO_ROOT_USER_FILE
              value: /etc/minio/secrets/username
            - name: MINIO_ROOT_PASSWORD_FILE
              value: /etc/minio/secrets/password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: minio-credentials
          secret:
            secretName: minio-credentials