name: CI

on:
  push:
    branches: ["**"]  
  workflow_dispatch:
jobs:

  lint:
    name: Lint Code and Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint Python code
        run: flake8 src/ tests/

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

  build:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --no-cache -t hivebox .
      
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: hivebox
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
      
      - name: Run container
        run: docker run -d -p 5000:5000 --name hivebox hivebox

      - name: Wait for container to be ready
        run: sleep 3

      - name: Smoke test /version
        run: |
          response=$(curl -s http://localhost:5000/version)
          echo "Response: $response"
          echo $response | grep -q '"version"' && echo "✅ passed" || exit 1

      - name: Stop container
        run: docker stop hivebox  
